let optionsMap = new Map([
  ['terms', [
    {value: 'any', content: 'Anywhere in the page'},
    {value: 'title', content: 'In the title of the page'},
    {value: 'body', content: 'In the text of the page'},                        
    {value: 'url', content: 'In the URL of the page'},
    {value: 'links', content: 'In links to the page'}
  ]],
  ['type', [
    {value: '', content: 'Any format'},
    {value: 'pdf', content: 'Adobe Acrobat PDF (.pdf)'},
    {value: 'ps', content: 'Adobe Postscript (.ps)'},
    {value: 'dwf', content: 'Autodesk DWF (.dwf)'},
    {value: 'kml', content: 'Google Earth KML (.kml)'},
    {value: 'kmz', content: 'Google Earth KMZ (.kmz)'},
    {value: 'xls', content: 'Microsoft Excel (.xls)'},
    {value: 'ppt', content: 'Microsoft PowerPoint (.ppt)'},
    {value: 'doc', content: 'Microsoft Word (.doc)'},
    {value: 'rtf', content: 'Rich Text Format (.rtf)'},
    {value: 'swf', content: 'Shockwave Flash (.swf)'},
    {value: 'mkv', content: 'Matroska Video (.mkv)'},
    {value: 'avi', content: 'Audio Video Interleave (.avi)'}
  ]],
  ['period', [
    {value: '', content: 'Anytime'},
    {value: 'd', content: 'Past 24 hours'},
    {value: 'w', content: 'Past week'},
    {value: 'm', content: 'Past month'},
    {value: 'y', content: 'Past year'}
  ]],
  ['language', [
    {value: '', content: 'Any language'},
    {value: 'lang_ar', content: 'Arabic'},
    {value: 'lang_hy', content: 'Armenian'},
    {value: 'lang_be', content: 'Belarusian'},
    {value: 'lang_bg', content: 'Bulgarian'},
    {value: 'lang_ca', content: 'Catalan'},
    {value: 'lang_zh-CN', content: 'Chinese Simplified'},
    {value: 'lang_zh-TW', content: 'Chinese Traditional'},
    {value: 'lang_hr', content: 'Croatian'},
    {value: 'lang_cs', content: 'Czech'},
    {value: 'lang_da', content: 'Danish'},
    {value: 'lang_nl', content: 'Dutch'},
    {value: 'lang_en', content: 'English'},
    {value: 'lang_eo', content: 'Esperanto'},
    {value: 'lang_et', content: 'Estonian'},
    {value: 'lang_tl', content: 'Filipino'},
    {value: 'lang_fi', content: 'Finnish'},
    {value: 'lang_fr', content: 'French'},
    {value: 'lang_de', content: 'German'},
    {value: 'lang_el', content: 'Greek'},
    {value: 'lang_iw', content: 'Hebrew'},
    {value: 'lang_hu', content: 'Hungarian'},
    {value: 'lang_is', content: 'Icelandic'},
    {value: 'lang_id', content: 'Indonesian'},
    {value: 'lang_it', content: 'Italian'},
    {value: 'lang_ja', content: 'Japanese'},
    {value: 'lang_ko', content: 'Korean'},
    {value: 'lang_lv', content: 'Latvian'},
    {value: 'lang_lt', content: 'Lithuanian'},
    {value: 'lang_no', content: 'Norwegian'},
    {value: 'lang_fa', content: 'Persian'},
    {value: 'lang_pl', content: 'Polish'},
    {value: 'lang_pt', content: 'Portuguese'},
    {value: 'lang_ro', content: 'Romanian'},
    {value: 'lang_ru', content: 'Russian'},
    {value: 'lang_sr', content: 'Serbian'},
    {value: 'lang_sk', content: 'Slovak'},
    {value: 'lang_sl', content: 'Slovenian'},
    {value: 'lang_es', content: 'Spanish'},
    {value: 'lang_sv', content: 'Swedish'},
    {value: 'lang_th', content: 'Thai'},
    {value: 'lang_tr', content: 'Turkish'},
    {value: 'lang_uk', content: 'Ukrainian'},
    {value: 'lang_vi', content: 'Vietnamese'},
  ]],
  ['region', [
    {value: '', content: 'Any region'},
    {value: 'countryAF', content: 'Afghanistan'},
    {value: 'countryAL', content: 'Albania'},
    {value: 'countryDZ', content: 'Algeria'},
    {value: 'countryAS', content: 'American Samoa'},
    {value: 'countryAD', content: 'Andorra'},
    {value: 'countryAO', content: 'Angola'},
    {value: 'countryAI', content: 'Anguilla'},
    {value: 'countryAQ', content: 'Antarctica'},
    {value: 'countryAG', content: 'Antigua &amp; Barbuda'},
    {value: 'countryAR', content: 'Argentina'},
    {value: 'countryAM', content: 'Armenia'},
    {value: 'countryAW', content: 'Aruba'},
    {value: 'countryAU', content: 'Australia'},
    {value: 'countryAT', content: 'Austria'},
    {value: 'countryAZ', content: 'Azerbaijan'},
    {value: 'countryBS', content: 'Bahamas'},
    {value: 'countryBH', content: 'Bahrain'},
    {value: 'countryBD', content: 'Bangladesh'},
    {value: 'countryBB', content: 'Barbados'},
    {value: 'countryBY', content: 'Belarus'},
    {value: 'countryBE', content: 'Belgium'},
    {value: 'countryBZ', content: 'Belize'},
    {value: 'countryBJ', content: 'Benin'},
    {value: 'countryBM', content: 'Bermuda'},
    {value: 'countryBT', content: 'Bhutan'},
    {value: 'countryBO', content: 'Bolivia'},
    {value: 'countryBA', content: 'Bosnia &amp; Herzegovina'},
    {value: 'countryBW', content: 'Botswana'},
    {value: 'countryBV', content: 'Bouvet Island'},
    {value: 'countryBR', content: 'Brazil'},
    {value: 'countryIO', content: 'British Indian Ocean Territory'},
    {value: 'countryVG', content: 'British Virgin Islands'},
    {value: 'countryBN', content: 'Brunei'},
    {value: 'countryBG', content: 'Bulgaria'},
    {value: 'countryBF', content: 'Burkina Faso'},
    {value: 'countryBI', content: 'Burundi'},
    {value: 'countryKH', content: 'Cambodia'},
    {value: 'countryCM', content: 'Cameroon'},
    {value: 'countryCA', content: 'Canada'},
    {value: 'countryCV', content: 'Cape Verde'},
    {value: 'countryKY', content: 'Cayman Islands'},
    {value: 'countryCF', content: 'Central African Republic'},
    {value: 'countryTD', content: 'Chad'},
    {value: 'countryCL', content: 'Chile'},
    {value: 'countryCN', content: 'China'},
    {value: 'countryCX', content: 'Christmas Island'},
    {value: 'countryCC', content: 'Cocos (Keeling) Islands'},
    {value: 'countryCO', content: 'Colombia'},
    {value: 'countryKM', content: 'Comoros'},
    {value: 'countryCG', content: 'Congo - Brazzaville'},
    {value: 'countryCD', content: 'Congo - Kinshasa'},
    {value: 'countryCK', content: 'Cook Islands'},
    {value: 'countryCR', content: 'Costa Rica'},
    {value: 'countryCI', content: 'Côte d’Ivoire'},
    {value: 'countryHR', content: 'Croatia'},
    {value: 'countryCU', content: 'Cuba'},
    {value: 'countryCY', content: 'Cyprus'},
    {value: 'countryCZ', content: 'Czechia'},
    {value: 'countryDK', content: 'Denmark'},
    {value: 'countryDJ', content: 'Djibouti'},
    {value: 'countryDM', content: 'Dominica'},
    {value: 'countryDO', content: 'Dominican Republic'},
    {value: 'countryEC', content: 'Ecuador'},
    {value: 'countryEG', content: 'Egypt'},
    {value: 'countrySV', content: 'El Salvador'},
    {value: 'countryGQ', content: 'Equatorial Guinea'},
    {value: 'countryER', content: 'Eritrea'},
    {value: 'countryEE', content: 'Estonia'},
    {value: 'countrySZ', content: 'Eswatini'},
    {value: 'countryET', content: 'Ethiopia'},
    {value: 'countryFK', content: 'Falkland Islands (Islas Malvinas)'},
    {value: 'countryFO', content: 'Faroe Islands'},
    {value: 'countryFJ', content: 'Fiji'},
    {value: 'countryFI', content: 'Finland'},
    {value: 'countryFR', content: 'France'},
    {value: 'countryGF', content: 'French Guiana'},
    {value: 'countryPF', content: 'French Polynesia'},
    {value: 'countryTF', content: 'French Southern Territories'},
    {value: 'countryGA', content: 'Gabon'},
    {value: 'countryGM', content: 'Gambia'},
    {value: 'countryGE', content: 'Georgia'},
    {value: 'countryDE', content: 'Germany'},
    {value: 'countryGH', content: 'Ghana'},
    {value: 'countryGI', content: 'Gibraltar'},
    {value: 'countryGR', content: 'Greece'},
    {value: 'countryGL', content: 'Greenland'},
    {value: 'countryGD', content: 'Grenada'},
    {value: 'countryGP', content: 'Guadeloupe'},
    {value: 'countryGU', content: 'Guam'},
    {value: 'countryGT', content: 'Guatemala'},
    {value: 'countryGN', content: 'Guinea'},
    {value: 'countryGW', content: 'Guinea-Bissau'},
    {value: 'countryGY', content: 'Guyana'},
    {value: 'countryHT', content: 'Haiti'},
    {value: 'countryHM', content: 'Heard &amp; McDonald Islands'},
    {value: 'countryHN', content: 'Honduras'},
    {value: 'countryHK', content: 'Hong Kong'},
    {value: 'countryHU', content: 'Hungary'},
    {value: 'countryIS', content: 'Iceland'},
    {value: 'countryIN', content: 'India'},
    {value: 'countryID', content: 'Indonesia'},
    {value: 'countryIR', content: 'Iran'},
    {value: 'countryIQ', content: 'Iraq'},
    {value: 'countryIE', content: 'Ireland'},
    {value: 'countryIL', content: 'Israel'},
    {value: 'countryIT', content: 'Italy'},
    {value: 'countryJM', content: 'Jamaica'},
    {value: 'countryJP', content: 'Japan'},
    {value: 'countryJO', content: 'Jordan'},
    {value: 'countryKZ', content: 'Kazakhstan'},
    {value: 'countryKE', content: 'Kenya'},
    {value: 'countryKI', content: 'Kiribati'},
    {value: 'countryKW', content: 'Kuwait'},
    {value: 'countryKG', content: 'Kyrgyzstan'},
    {value: 'countryLA', content: 'Laos'},
    {value: 'countryLV', content: 'Latvia'},
    {value: 'countryLB', content: 'Lebanon'},
    {value: 'countryLS', content: 'Lesotho'},
    {value: 'countryLR', content: 'Liberia'},
    {value: 'countryLY', content: 'Libya'},
    {value: 'countryLI', content: 'Liechtenstein'},
    {value: 'countryLT', content: 'Lithuania'},
    {value: 'countryLU', content: 'Luxembourg'},
    {value: 'countryMO', content: 'Macao'},
    {value: 'countryMG', content: 'Madagascar'},
    {value: 'countryMW', content: 'Malawi'},
    {value: 'countryMY', content: 'Malaysia'},
    {value: 'countryMV', content: 'Maldives'},
    {value: 'countryML', content: 'Mali'},
    {value: 'countryMT', content: 'Malta'},
    {value: 'countryMH', content: 'Marshall Islands'},
    {value: 'countryMQ', content: 'Martinique'},
    {value: 'countryMR', content: 'Mauritania'},
    {value: 'countryMU', content: 'Mauritius'},
    {value: 'countryYT', content: 'Mayotte'},
    {value: 'countryMX', content: 'Mexico'},
    {value: 'countryFM', content: 'Micronesia'},
    {value: 'countryMD', content: 'Moldova'},
    {value: 'countryMC', content: 'Monaco'},
    {value: 'countryMN', content: 'Mongolia'},
    {value: 'countryMS', content: 'Montserrat'},
    {value: 'countryMA', content: 'Morocco'},
    {value: 'countryMZ', content: 'Mozambique'},
    {value: 'countryMM', content: 'Myanmar (Burma)'},
    {value: 'countryNA', content: 'Namibia'},
    {value: 'countryNR', content: 'Nauru'},
    {value: 'countryNP', content: 'Nepal'},
    {value: 'countryNL', content: 'Netherlands'},
    {value: 'countryNC', content: 'New Caledonia'},
    {value: 'countryNZ', content: 'New Zealand'},
    {value: 'countryNI', content: 'Nicaragua'},
    {value: 'countryNE', content: 'Niger'},
    {value: 'countryNG', content: 'Nigeria'},
    {value: 'countryNU', content: 'Niue'},
    {value: 'countryNF', content: 'Norfolk Island'},
    {value: 'countryKP', content: 'North Korea'},
    {value: 'countryMK', content: 'North Macedonia'},
    {value: 'countryMP', content: 'Northern Mariana Islands'},
    {value: 'countryNO', content: 'Norway'},
    {value: 'countryOM', content: 'Oman'},
    {value: 'countryPK', content: 'Pakistan'},
    {value: 'countryPW', content: 'Palau'},
    {value: 'countryPS', content: 'Palestine'},
    {value: 'countryPA', content: 'Panama'},
    {value: 'countryPG', content: 'Papua New Guinea'},
    {value: 'countryPY', content: 'Paraguay'},
    {value: 'countryPE', content: 'Peru'},
    {value: 'countryPH', content: 'Philippines'},
    {value: 'countryPN', content: 'Pitcairn Islands'},
    {value: 'countryPL', content: 'Poland'},
    {value: 'countryPT', content: 'Portugal'},
    {value: 'countryPR', content: 'Puerto Rico'},
    {value: 'countryQA', content: 'Qatar'},
    {value: 'countryRE', content: 'Réunion'},
    {value: 'countryRO', content: 'Romania'},
    {value: 'countryRU', content: 'Russia'},
    {value: 'countryRW', content: 'Rwanda'},
    {value: 'countryWS', content: 'Samoa'},
    {value: 'countrySM', content: 'San Marino'},
    {value: 'countryST', content: 'São Tomé &amp; Príncipe'},
    {value: 'countrySA', content: 'Saudi Arabia'},
    {value: 'countrySN', content: 'Senegal'},
    {value: 'countryRS', content: 'Serbia'},
    {value: 'countrySC', content: 'Seychelles'},
    {value: 'countrySL', content: 'Sierra Leone'},
    {value: 'countrySG', content: 'Singapore'},
    {value: 'countrySK', content: 'Slovakia'},
    {value: 'countrySI', content: 'Slovenia'},
    {value: 'countrySB', content: 'Solomon Islands'},
    {value: 'countrySO', content: 'Somalia'},
    {value: 'countryZA', content: 'South Africa'},
    {value: 'countryGS', content: 'South Georgia &amp; South Sandwich Islands'},
    {value: 'countryKR', content: 'South Korea'},
    {value: 'countryES', content: 'Spain'},
    {value: 'countryLK', content: 'Sri Lanka'},
    {value: 'countrySH', content: 'St. Helena'},
    {value: 'countryKN', content: 'St. Kitts &amp; Nevis'},
    {value: 'countryLC', content: 'St. Lucia'},
    {value: 'countryPM', content: 'St. Pierre &amp; Miquelon'},
    {value: 'countryVC', content: 'St. Vincent &amp; Grenadines'},
    {value: 'countrySD', content: 'Sudan'},
    {value: 'countrySR', content: 'Suriname'},
    {value: 'countrySJ', content: 'Svalbard &amp; Jan Mayen'},
    {value: 'countrySE', content: 'Sweden'},
    {value: 'countryCH', content: 'Switzerland'},
    {value: 'countrySY', content: 'Syria'},
    {value: 'countryTW', content: 'Taiwan'},
    {value: 'countryTJ', content: 'Tajikistan'},
    {value: 'countryTZ', content: 'Tanzania'},
    {value: 'countryTH', content: 'Thailand'},
    {value: 'countryTG', content: 'Togo'},
    {value: 'countryTK', content: 'Tokelau'},
    {value: 'countryTO', content: 'Tonga'},
    {value: 'countryTT', content: 'Trinidad &amp; Tobago'},
    {value: 'countryTN', content: 'Tunisia'},
    {value: 'countryTR', content: 'Türkiye'},
    {value: 'countryTM', content: 'Turkmenistan'},
    {value: 'countryTC', content: 'Turks &amp; Caicos Islands'},
    {value: 'countryTV', content: 'Tuvalu'},
    {value: 'countryUM', content: 'U.S. Outlying Islands'},
    {value: 'countryVI', content: 'U.S. Virgin Islands'},
    {value: 'countryUG', content: 'Uganda'},
    {value: 'countryUA', content: 'Ukraine'},
    {value: 'countryAE', content: 'United Arab Emirates'},
    {value: 'countryGB', content: 'United Kingdom'},
    {value: 'countryUS', content: 'United States'},
    {value: 'countryUY', content: 'Uruguay'},
    {value: 'countryUZ', content: 'Uzbekistan'},
    {value: 'countryVU', content: 'Vanuatu'},
    {value: 'countryVA', content: 'Vatican City'},
    {value: 'countryVE', content: 'Venezuela'},
    {value: 'countryVN', content: 'Vietnam'},
    {value: 'countryWF', content: 'Wallis &amp; Futuna'},
    {value: 'countryEH', content: 'Western Sahara'},
    {value: 'countryYE', content: 'Yemen'},
    {value: 'countryZM', content: 'Zambia'},
    {value: 'countryZW', content: 'Zimbabwe'}
  ]],
]);                    


